// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/hisport/historical_portfolio.proto

package hisport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoricalPortfolioService_Create_FullMethodName            = "/historical_portfolio.HistoricalPortfolioService/Create"
	HistoricalPortfolioService_GetPortfolioValue_FullMethodName = "/historical_portfolio.HistoricalPortfolioService/GetPortfolioValue"
	HistoricalPortfolioService_GetGain_FullMethodName           = "/historical_portfolio.HistoricalPortfolioService/GetGain"
)

// HistoricalPortfolioServiceClient is the client API for HistoricalPortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoricalPortfolioServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPortfolioValue(ctx context.Context, in *GetPortfolioValueReq, opts ...grpc.CallOption) (*GetPortfolioValueRes, error)
	GetGain(ctx context.Context, in *GetGainReq, opts ...grpc.CallOption) (*GetGainRes, error)
}

type historicalPortfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoricalPortfolioServiceClient(cc grpc.ClientConnInterface) HistoricalPortfolioServiceClient {
	return &historicalPortfolioServiceClient{cc}
}

func (c *historicalPortfolioServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HistoricalPortfolioService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historicalPortfolioServiceClient) GetPortfolioValue(ctx context.Context, in *GetPortfolioValueReq, opts ...grpc.CallOption) (*GetPortfolioValueRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPortfolioValueRes)
	err := c.cc.Invoke(ctx, HistoricalPortfolioService_GetPortfolioValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historicalPortfolioServiceClient) GetGain(ctx context.Context, in *GetGainReq, opts ...grpc.CallOption) (*GetGainRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGainRes)
	err := c.cc.Invoke(ctx, HistoricalPortfolioService_GetGain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoricalPortfolioServiceServer is the server API for HistoricalPortfolioService service.
// All implementations must embed UnimplementedHistoricalPortfolioServiceServer
// for forward compatibility.
type HistoricalPortfolioServiceServer interface {
	Create(context.Context, *CreateReq) (*emptypb.Empty, error)
	GetPortfolioValue(context.Context, *GetPortfolioValueReq) (*GetPortfolioValueRes, error)
	GetGain(context.Context, *GetGainReq) (*GetGainRes, error)
	mustEmbedUnimplementedHistoricalPortfolioServiceServer()
}

// UnimplementedHistoricalPortfolioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoricalPortfolioServiceServer struct{}

func (UnimplementedHistoricalPortfolioServiceServer) Create(context.Context, *CreateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedHistoricalPortfolioServiceServer) GetPortfolioValue(context.Context, *GetPortfolioValueReq) (*GetPortfolioValueRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolioValue not implemented")
}
func (UnimplementedHistoricalPortfolioServiceServer) GetGain(context.Context, *GetGainReq) (*GetGainRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGain not implemented")
}
func (UnimplementedHistoricalPortfolioServiceServer) mustEmbedUnimplementedHistoricalPortfolioServiceServer() {
}
func (UnimplementedHistoricalPortfolioServiceServer) testEmbeddedByValue() {}

// UnsafeHistoricalPortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoricalPortfolioServiceServer will
// result in compilation errors.
type UnsafeHistoricalPortfolioServiceServer interface {
	mustEmbedUnimplementedHistoricalPortfolioServiceServer()
}

func RegisterHistoricalPortfolioServiceServer(s grpc.ServiceRegistrar, srv HistoricalPortfolioServiceServer) {
	// If the following call pancis, it indicates UnimplementedHistoricalPortfolioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoricalPortfolioService_ServiceDesc, srv)
}

func _HistoricalPortfolioService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalPortfolioServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalPortfolioService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalPortfolioServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoricalPortfolioService_GetPortfolioValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalPortfolioServiceServer).GetPortfolioValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalPortfolioService_GetPortfolioValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalPortfolioServiceServer).GetPortfolioValue(ctx, req.(*GetPortfolioValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoricalPortfolioService_GetGain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalPortfolioServiceServer).GetGain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalPortfolioService_GetGain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalPortfolioServiceServer).GetGain(ctx, req.(*GetGainReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoricalPortfolioService_ServiceDesc is the grpc.ServiceDesc for HistoricalPortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoricalPortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "historical_portfolio.HistoricalPortfolioService",
	HandlerType: (*HistoricalPortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _HistoricalPortfolioService_Create_Handler,
		},
		{
			MethodName: "GetPortfolioValue",
			Handler:    _HistoricalPortfolioService_GetPortfolioValue_Handler,
		},
		{
			MethodName: "GetGain",
			Handler:    _HistoricalPortfolioService_GetGain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hisport/historical_portfolio.proto",
}
