// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// bluePrintFunc is an autogenerated mock type for the bluePrintFunc type
type bluePrintFunc[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: i, last
func (_m *bluePrintFunc[T]) Execute(i int, last T) T {
	ret := _m.Called(i, last)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func(int, T) T); ok {
		r0 = rf(i, last)
	} else {
		r0 = ret.Get(0).(T)
	}

	return r0
}

// newBluePrintFunc creates a new instance of bluePrintFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBluePrintFunc[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *bluePrintFunc[T] {
	mock := &bluePrintFunc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
