// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/eyo-chen/expense-tracker-go/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// IconUC is an autogenerated mock type for the IconUC type
type IconUC struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *IconUC) List() ([]domain.Icon, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Icon
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Icon, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Icon); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Icon)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIconUC creates a new instance of IconUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIconUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *IconUC {
	mock := &IconUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
