// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/OYE0303/expense-tracker-go/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// IconModel is an autogenerated mock type for the IconModel type
type IconModel struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *IconModel) GetByID(id int64) (domain.Icon, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Icon
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (domain.Icon, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) domain.Icon); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Icon)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *IconModel) List() ([]domain.Icon, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Icon
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Icon, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Icon); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Icon)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIconModel creates a new instance of IconModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIconModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *IconModel {
	mock := &IconModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
