// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debugw provides a mock function with given fields: msg, options
func (_m *Logger) Debugw(msg string, options ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, options...)
	_m.Called(_ca...)
}

// Errorw provides a mock function with given fields: msg, options
func (_m *Logger) Errorw(msg string, options ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, options...)
	_m.Called(_ca...)
}

// Fatalw provides a mock function with given fields: msg, options
func (_m *Logger) Fatalw(msg string, options ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, options...)
	_m.Called(_ca...)
}

// Infow provides a mock function with given fields: msg, options
func (_m *Logger) Infow(msg string, options ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, options...)
	_m.Called(_ca...)
}

// Panicw provides a mock function with given fields: msg, options
func (_m *Logger) Panicw(msg string, options ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, options...)
	_m.Called(_ca...)
}

// Warnw provides a mock function with given fields: msg, options
func (_m *Logger) Warnw(msg string, options ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, options...)
	_m.Called(_ca...)
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
