// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RedisService is an autogenerated mock type for the RedisService type
type RedisService struct {
	mock.Mock
}

// GetByFunc provides a mock function with given fields: ctx, key, f
func (_m *RedisService) GetByFunc(ctx context.Context, key string, f func() (string, error)) (string, error) {
	ret := _m.Called(ctx, key, f)

	if len(ret) == 0 {
		panic("no return value specified for GetByFunc")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func() (string, error)) (string, error)); ok {
		return rf(ctx, key, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, func() (string, error)) string); ok {
		r0 = rf(ctx, key, f)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, func() (string, error)) error); ok {
		r1 = rf(ctx, key, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRedisService creates a new instance of RedisService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisService {
	mock := &RedisService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
