// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// setTraiter is an autogenerated mock type for the setTraiter type
type setTraiter[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: v
func (_m *setTraiter[T]) Execute(v *T) {
	_m.Called(v)
}

// newSetTraiter creates a new instance of setTraiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSetTraiter[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *setTraiter[T] {
	mock := &setTraiter[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
