// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserIconUC is an autogenerated mock type for the UserIconUC type
type UserIconUC struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, fileName, userID
func (_m *UserIconUC) Create(ctx context.Context, fileName string, userID int64) error {
	ret := _m.Called(ctx, fileName, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, fileName, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPutObjectURL provides a mock function with given fields: ctx, fileName, userID
func (_m *UserIconUC) GetPutObjectURL(ctx context.Context, fileName string, userID int64) (string, error) {
	ret := _m.Called(ctx, fileName, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPutObjectURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return rf(ctx, fileName, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, fileName, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, fileName, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserIconUC creates a new instance of UserIconUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserIconUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserIconUC {
	mock := &UserIconUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
