name: Let's Deploy Cron Lambda

on:
  workflow_run:
    workflows: ["Let's Go CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy-lambda:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Check if relevant files changed
        id: check-changes
        run: |
          RELEVANT=false
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == cmd/cron/* ]]; then
              RELEVANT=true
              break
            fi
          done
          if [ "$RELEVANT" = "false" ]; then
            echo "No relevant files changed, skipping deployment"
            exit 78  # Special exit code that GitHub Actions recognizes as neutral
          fi

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Lambda Function
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap cmd/cron/main.go
          zip go-lambda.zip bootstrap

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://go-lambda.zip